version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  default:
    docker:
      - image: cimg/node:16.15.1


aliases: [
  # List of dependency paths that should be persisted to the
  # CircleCI workspace.
  &dependency-paths [
    "node_modules"
  ],

  # List of build output paths that should be persisted to the
  # CircleCI workspace.
  &build-output-paths [
    "dist",
  ],

  # NPM lockfile cache key (update "vN" => "vN+1" to cache-bust).
  &dependency-cache-key "v2-dependency-cache-{{ checksum \"yarn.lock\" }}",

  &workspace-root "/home/circleci/project",

  &attach-workspace {
    attach_workspace: {
      at: *workspace-root
    }
  },

  # Filter pull requests not in "master" or "next" (development code)
  &filter-default-branches {
    filters: {
      branches: {
        ignore: "/^master$|^next$/"
      }
    }
  },

  # Filter pull requests in "master" or "next" only (production code).
  &filter-release-branches-only {
    filters: {
      branches: {
        only: [
          "master",
          "next",
        ]
      }
    }
  }
]

jobs:
  install-dependencies:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - node/install-packages:
          check-cache: detect 
          pkg-manager: yarn
      - persist_to_workspace:
          paths: *dependency-paths
          root: *workspace-root
  lint:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Lint source files
          command: yarn run lint

  build:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Build modules
          command: yarn build
      - persist_to_workspace:
          paths: *build-output-paths
          root: *workspace-root

  test:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Run unit tests
          command: yarn test
      - store_artifacts:
          path: coverage



workflows:
  pull-request:
    jobs:
      - install-dependencies: *filter-default-branches
      - build:
          requires:
            - install-dependencies
      - test:
          requires:
            - build
      - lint:
          requires:
            - build