version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  default:
    docker:
      - image: cimg/node:16.15.1

aliases: [
  # List of dependency paths that should be persisted to the
  # CircleCI workspace.
  &dependency-paths [
    "node_modules"
  ],

  # List of build output paths that should be persisted to the
  # CircleCI workspace.
  &build-output-paths [
    "dist",
  ],

  &workspace-root "/home/circleci/project",

  &attach-workspace {
    attach_workspace: {
      at: *workspace-root
    }
  },

  # Filter pull requests not in "master" or "stage" (development code)
  &filter-default-branches {
    filters: {
      branches: {
        ignore: "/^master$|^stage$/"
      }
    }
  },  
]

jobs:
  install-dependencies:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - node/install-packages:
          check-cache: detect 
          pkg-manager: yarn
      - persist_to_workspace:
          paths: *dependency-paths
          root: *workspace-root

  build:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Build modules
          command: yarn build
      - persist_to_workspace:
          paths: *build-output-paths
          root: *workspace-root

  lint:
    executor: default
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Lint source files
          command: yarn run lint

  test:
    executor: default
    parallelism: 3
    steps:
      - checkout
      - *attach-workspace
      - run:
          name: Run unit tests
          command: |
            mkdir -p  ./artifacts/test-results/jest
            yarn test --ci --testResultsProcessor=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_FILE: ./artifacts/test-results/jest/jest.xml
      - store_artifacts:
          path: ./artifacts



workflows:
  pull-request:
    jobs:
      - install-dependencies: *filter-default-branches
      - build:
          requires:
            - install-dependencies
      - test:
          requires:
            - build
      - lint:
          requires:
            - build