version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - node/install-packages:
          pkg-manager: yarn
          check-cache: detect
      - run: yarn lint
      - run: yarn build
      - run: yarn test
      - store_test_results:
          path: test-results

workflows:
  build:
    jobs:
      - build
