version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    working_directory: ~/recipes-server
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn build
      - run:
          name: Jest tests
          command: |
            mkdir -p  /tmp/artifacts/test-results
            yarn test --ci --collectCoverage --reporters=default --reporters=jest-junit --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT_FILE: /tmp/artifacts/test-results/jest.xml
      - store_artifacts:
          path: /tmp/artifacts
      - store_test_results:
          path: /tmp/artifacts/test-results

workflows:
  build:
    jobs:
      - build
